### ISSUE TITLE
ghost_communicator example fails

### ISSUE THREAD

**Issue by mscroggs** [linalg-rs/rlst#19]
If I run this example:

```bash
cargo mpirun --example ghost_communicator --release -n 2 --features "mpi"
```

I get the error:

```
thread 'main' panicked at 'assertion failed: `(left != right)`
  left: `0`,
 right: `0`: Index 1 already exists on rank 0.', /rlst/sparse/src/ghost_communicator.rs:38:13
```

**Comment by jedbrown** [comment]
Huh, I see this, and it seems like `MPI_UNWEIGHTED` is not bound in `mpi-sys` and `Topology::Graph` is unimplemented. Did you add it in a branch?
```
error[E0425]: cannot find value `MPI_UNWEIGHTED` in crate `mpi_sys`
   --> sparse/src/ghost_communicator.rs:108:26
    |
108 |                 mpi_sys::MPI_UNWEIGHTED,
    |                          ^^^^^^^^^^^^^^ not found in `mpi_sys`

error[E0425]: cannot find value `MPI_UNWEIGHTED` in crate `mpi_sys`
   --> sparse/src/ghost_communicator.rs:111:26
    |
111 |                 mpi_sys::MPI_UNWEIGHTED,
    |                          ^^^^^^^^^^^^^^ not found in `mpi_sys`
```

**Comment by mscroggs** [comment]
> Huh, I see this, and it seems like `MPI_UNWEIGHTED` is not bound in `mpi-sys` and `Topology::Graph` is unimplemented. Did you add it in a branch?
> 
> ```
> error[E0425]: cannot find value `MPI_UNWEIGHTED` in crate `mpi_sys`
>    --> sparse/src/ghost_communicator.rs:108:26
>     |
> 108 |                 mpi_sys::MPI_UNWEIGHTED,
>     |                          ^^^^^^^^^^^^^^ not found in `mpi_sys`
> 
> error[E0425]: cannot find value `MPI_UNWEIGHTED` in crate `mpi_sys`
>    --> sparse/src/ghost_communicator.rs:111:26
>     |
> 111 |                 mpi_sys::MPI_UNWEIGHTED,
>     |                          ^^^^^^^^^^^^^^ not found in `mpi_sys`
> ```

I'm seeing the MPI_UNWEIGHTED ERROR only when using openmpi. With mpich, I get this fail instead.

I've opened #20 for the MPI_UNWEIGHTED error
