### ISSUE TITLE
build fails with openmpi

### ISSUE THREAD

**Issue by mscroggs** [linalg-rs/rlst#20]
I'm getting the error ``cannot find value `MPI_UNWEIGHTED` in crate `mpi_sys` `` when trying to build RLST in a Ubuntu with openmpi.

In case it's useful, here's a Dockerfile that tries to install RLST with openmpi. Building this leads to the error. If I change `libopenmpi-dev` to `libmpich-dev`, the build is successful.

```docker
FROM ubuntu:22.04 as rust-test

RUN apt-get update
RUN apt-get -y install libopenmpi-dev libopenblas-dev liblapack-dev libclang-dev \
    git curl pkg-config libssl-dev build-essential
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
RUN git clone https://github.com/mscroggs/rlst.git
RUN cd rlst && RUST_BACKTRACE=full $HOME/.cargo/bin/cargo build --features "strict,mpi"
```

**Comment by jedbrown** [comment]
This is why.
```console
$ rg MPI_UNWEIGHT /usr/include/mpi.h /opt/mpich/include/mpi.h
/usr/include/mpi.h
520:#define MPI_UNWEIGHTED           ((int *) 2)           /* unweighted graph */

/opt/mpich/include/mpi.h
388:extern int * const MPI_UNWEIGHTED MPICH_API_PUBLIC;
```

 It needs to be exported by `mpi-sys/src/rsmpi.{h,c}`. Would you be willing to contribute this to rsmpi? You can use `RSMPI_STATUS_IGNORE` as a model.

**Comment by mscroggs** [comment]
I'll give it a go
